### ISSUE TITLE
Doesn't work on node v18.12.1?

### ISSUE THREAD

**Issue by qxb3** [ilearnio/module-alias#133]
## index.js

```js
require('module-alias/register')
...
```

## `package.json`

```js
{
  ...
  "_moduleAliases": {
    "#root": "./",
    "#src": "./src",
    "#routes": "./src/routes",
    "#lib": "./src/lib",
    "#utils": "./src/lib/utils",
    "#models": "./src/lib/models",
    "#decors": "./src/lib/decors",
    "#schemas": "./src/lib/schemas"
  }
  ...
}
```

## `versions`

**node: v18.21.1**
**module-alias: 2.2.2**

**Comment by chaeyan** [comment]
and the error??

**Comment by girixcode7** [comment]
@qxb3 How did you resolve this issue?
In case of mine It throws Can't Find module ?
```
node:internal/modules/cjs/loader:1042
  throw err;
  ^
Error: Cannot find module '@routersV1/users/usersRouter'
```


## package.json
```
"_moduleAliases": {
 "@routersV1/*": "./src/routers/v1/*"
}
```
## Nodejs: v18.13.0

**Comment by qxb3** [comment]
@girixcode7 i didn't i instead use this: #113

**Comment by ugeshgupta000** [comment]
Follow this: https://medium.com/zero-equals-false/how-to-use-module-path-aliases-in-visual-studio-typescript-and-javascript-e7851df8eeaa

You might be missing the aliases in tsconfig.json
